function get_menu_input()
{
	key_left = input_check(INPUTS.ui_left)
	key_left_pressed = input_check_pressed(INPUTS.ui_left)
	key_right = input_check(INPUTS.ui_right)
	key_right_pressed = input_check_pressed(INPUTS.ui_right)
	key_up = input_check(INPUTS.ui_up)
	key_up_pressed = input_check_pressed(INPUTS.ui_up)
	key_down = input_check(INPUTS.ui_down)
	key_down_pressed = input_check_pressed(INPUTS.ui_down)
	key_jump = input_check(INPUTS.ui_confirm)
	key_jump_pressed = input_check_pressed(INPUTS.ui_confirm)
	key_grab = input_check(INPUTS.ui_quit)
	key_grab_pressed = input_check_pressed(INPUTS.ui_quit)
	key_taunt = input_check(INPUTS.ui_delete)
	key_taunt_pressed = input_check_pressed(INPUTS.ui_delete)
	key_start = input_check(INPUTS.ui_start)
	key_start_pressed = input_check_pressed(INPUTS.ui_start)
}
